apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyterhub-home-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
  - vers=4.1
  - proto=tcp
  - rsize=1048576
  - wsize=1048576
  - timeo=600
  - hard
  - retrans=2
  - noresvport
  nfs:
    server: 172.28.138.82
    path: /
